### ISSUE TITLE
Broken search?

### ISSUE THREAD

**Issue by chankeypathak** [novoselrok/codesnippetsearch#1]
Below query does not return results which have dask in the source.

https://codesnippetsearch.net/search?query=dask

**Comment by novoselrok** [comment]
Sorry about that, server was under a heavy load and everything grinded to a halt. It should be working now.

**Comment by chankeypathak** [comment]
I meant that the results are not accurate. If you click on the link that I shared, you'll notice that the result snippets don't have the word "dask" in them.

**Comment by novoselrok** [comment]
Right, sorry about the confusion. I think that the CodeSearchNet corpus does not contain any "dask" related functions, that is why there aren't any found. I'll check by hand if there any present, but that is most likely the cause.

**Comment by chankeypathak** [comment]
Wouldn't it be better to return "not found" in that case?

**Comment by novoselrok** [comment]
That would be ideal, yes. I could automatically exclude search results that have a match rating below 50%. But sometimes a search result with a poor match rating could still be useful. I would need much more code snippets to improve the search results and improve the model itself.

**Comment by chankeypathak** [comment]
I agree. The bigger the corpus, better the results.
